### ISSUE TITLE
Cosmetic changes

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/chatgse-next#1]
Goals: 

- [x] Edit page title
- [x] Add BioChatter favico
- [x] Update titles, subtitles, and other texts
- [x] Replace the Mask concept with Persona

**Comment by agdiaz** [comment]
<img width="1214" alt="image" src="https://github.com/biocypher/chatgse-next/assets/1646576/e89b0f7b-b629-40bb-8d3e-1f695979d714">
