### ISSUE TITLE
Question: do we compress messages?

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/chatgse-next#10]
The default in the app says message compression threshold is 1000 tokens. Is this active?

**Comment by fengsh27** [comment]
@slobentanzer this option is turned on. When the number of history messages is bigger than the threshold or max token, it will start compression: the app will raise a summarization request to ChatGPT and replace history messages with the summarization.

**Comment by slobentanzer** [comment]
Does this already interface with BioChatter, i.e., the conversation class history, or is this only in the frontend?

**Comment by fengsh27** [comment]
I'm not very sure what you mean by "interface with BioChatter". But the task of determining whether history messages require compression occurs in frontend.
Once frontend find the need to compress history messages, it will raise a summarization request to biochatter-server.
Here is the code to check if it requires history messages compression and send summarization request:
https://github.com/biocypher/chatgse-next/blob/1b8341eb2ec2740a15d8bafdc0210b3aefb9a810/chatgse/app/store/chat.ts#L479C1-L479C1

**Comment by slobentanzer** [comment]
@fengsh27 with 'interfacing' I mean the conversation history of the `Conversation` classes we have in BioChatter. If we summarise the previous conversation with the user, is the `Conversation` class history updated to reflect the current state of the conversation, i.e., are the previous parts of the history removed in the Python instance of the `Conversation`?

**Comment by fengsh27** [comment]
@slobentanzer Yes, every time a chat request is passed to biochatter, chat message history will be passed and used to update biochatter.
