### ISSUE TITLE
Cosmetic: RAG/KG button header at the bottom

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/chatgse-next#37]

**Comment by fengsh27** [comment]
@slobentanzer What is this issue for? I'm not very clear, would you please explain to me?

**Comment by fengsh27** [comment]
@slobentanzer is this issue relate to KG button disappearing at the bottom?

**Comment by slobentanzer** [comment]
@fengsh27 sorry this and other recent ones were just a bunch of issues I created mainly for myself to remind myself of the cosmetics that mysteriously disappeared from my commits. I will take care of them, probably tomorrow. :)

(it is about creating a header similar to the one containing the Help and Persona buttons, but for RAG and KG)
